### PR TITLE
Removing ntp recipe. We have a separate ntp cookbook.

### PR DESCRIPTION
**Pull request by dmatthew**

### CODE REVIEW

**Comment by colby** [comment]
I'm wondering if it would be worth including the new NTP cookbook into this one?

**Comment by dmatthew** [comment]
So adding the NTP cookbook as a dependency to the base cookbook, and using it in here? Or getting rid of the NTP cookbook and moving its code into this base cookbook?

**Comment by colby** [comment]
Making the NTP cookbook a dependency.

**Comment by dmatthew** [comment]
Fine by me. I can do that.

**Pull request merged**
